#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | nginx-options:help)
    help_content_func () {
      declare desc="return help_content string"
      cat<<nginx_options_content
    nginx-options:client-max-body-size <app> <size>, Set the max size of a client request
    nginx-options:remove <app>, Remove all configuration
nginx_options_content
    }

    if [[ $1 = "nginx-options:help" ]] ; then
        echo -e 'Usage: dokku nginx-options:command [<app>]'
        echo ''
        echo 'Set nginx options on <app>.'
        echo ''
        echo 'Example:'
        echo ''
        echo '$ dokku nginx-options:client-max-body-size app 1m'
        echo ''
        help_content_func | sort | column -c2 -t -s,
    else
        help_content_func
    fi
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
