#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

nginx_options_client_max_body_size_cmd() {
  declare desc="Set the maximum size of a client request allowed to flow through nginx"
  local cmd="nginx-options:client-max-body-size"
  # Support --app/$DOKKU_APP_NAME flag
  # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
  verify_app_name "$2"
  local APP="$2";

  if [ -z "$3" ]; then
    echo "Please specify the max body size"
    exit 1
  fi

  # source an existing configuration file if any
  if [ -f $DOKKU_ROOT/$APP/nginx-options.conf ]; then
    . $DOKKU_ROOT/$APP/nginx-options.conf
  fi

  # override value of the current max body size
  CLIENT_MAX_BODY_SIZE="$3"

  # override config file (with the new option)
  cat <<EOF > $DOKKU_ROOT/$APP/nginx-options.conf
CLIENT_MAX_BODY_SIZE=${CLIENT_MAX_BODY_SIZE}
EOF

  # create nginx.conf.d directory if not already existing
  mkdir -p $DOKKU_ROOT/$APP/nginx.conf.d

  # update the nginx conf file with the new options
  cat <<EOF > $DOKKU_ROOT/$APP/nginx.conf.d/nginx-options.conf
client_max_body_size ${CLIENT_MAX_BODY_SIZE};
EOF
}

nginx_options_client_max_body_size_cmd "$@"
