#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

nginx_options_remove_cmd() {
  declare desc="Deactivate the plugin by removing all configuration"
  local cmd="nginx-options:remove"
  # Support --app/$DOKKU_APP_NAME flag
  # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
  verify_app_name "$2"
  local APP="$2";

  if [ -f "$DOKKU_ROOT/$APP/nginx-options.conf" ]; then
    rm "$DOKKU_ROOT/$APP/nginx-options.conf"
  fi

  if [ -f "$DOKKU_ROOT/$APP/nginx.conf.d/nginx-options.conf" ]; then
    rm "$DOKKU_ROOT/$APP/nginx.conf.d/nginx-options.conf"
  fi
  
}

nginx_options_remove_cmd "$@"
